version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: nest_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - db
    command: sh -c "npm install && npm run start:dev"

  db:
    image: mysql:8  # Change to postgres:14-alpine for PostgreSQL
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
    volumes:
      - dbdata:/var/lib/mysql  # Change to /var/lib/postgresql/data for PostgreSQL
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'

volumes:
  dbdata:
